name: 测试

on:
  repository_dispatch:
    types: [cs,sshcs]
  workflow_dispatch:
    inputs:
      ssh:
        description: 'cs'
        required: false
        default: 'false'
#  schedule:
#    - cron: 00 17 * * *

env:
  TZ: Asia/Shanghai
  FILE_NAME: 测试

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: origan
      run: |
        cd /opt
        sudo wget https://downloads.openwrt.org/releases/19.07.4/targets/armvirt/64/openwrt-sdk-19.07.4-armvirt-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz
        sudo tar -xvJf *.tar.xz
        cd openwrt-sdk-19.07.4-armvirt-64_gcc-7.5.0_musl.Linux-x86_64
        git clone https://github.com/wlfit80/luci-app-koolproxyR.git package/luci-app-koolproxyR

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'sshcs')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: compile
      run: |
        cd /opt/openwrt-sdk-19.07.4-armvirt-64_gcc-7.5.0_musl.Linux-x86_64
        sudo make package/luci-app-koolproxyR/compile V=99
        sudo mv bin /opt/bin

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      with:
        name: cs
        path: /opt/bin
