name: 测试

on:
  repository_dispatch:
    types: [cs,sshcs]
  workflow_dispatch:
    inputs:
      ssh:
        description: 'cs'
        required: false
        default: 'false'
#  schedule:
#    - cron: 00 17 * * *

env:
  TZ: Asia/Shanghai
  FILE_NAME: 测试

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: origan
      run: |
        cd /home
        sudo wget https://downloads.openwrt.org/snapshots/targets/armvirt/64/openwrt-sdk-armvirt-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        sudo tar -xvJf *.tar.xz
        cd openwrt-sdk-armvirt-64_gcc-8.4.0_musl.Linux-x86_64
        sudo git clone https://github.com/bin20088/luci-app-koolproxy.git package/luci-app-koolproxy

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'sshcs')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: compile
      run: |
        cd /home/openwrt-sdk-armvirt-64_gcc-8.4.0_musl.Linux-x86_64
        sudo make package/luci-app-koolproxy/compile V=99
        sudo mv bin /home/bin

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      with:
        name: cs
        path: /home/bin

    - name: WeChat notification
      run: curl https://sc.ftqq.com/${{ secrets.ServerChan }}.send?text=${{ env.FILE_NAME }}编译结束
